module.exports.variables = {
    module_economy: true,
    module_serverStores: true,
    module_serverProfiles: true,
    module_fun: true,
    module_misc: true,
    module_basic: true,
    module_autoreact: true,
    module_nsfw: false,
    module_utility: true,
    module_tools: true,
    module_info: true,
    module_music: false,
    module_radios: true,
    module_settings: true,
    module_moderation: true,
    module_management: true,
    module_autoPublish: false,
    module_messageLogs: false,
    module_joinMessages: false,
    module_leaveMessages: false,
    module_statsChannel: false,
    module_customCommands: false,
    module_allowedChannels: false,
}