module.exports.variables = {
    module_economy: true,
    module_serverstores: true,
    module_serverprofiles: true,
    module_fun: true,
    module_misc: true,
    module_basic: true,
    module_autoreact: true,
    module_nsfw: false,
    module_utility: true,
    module_tools: true,
    module_info: true,
    module_music: true,
    module_radios: true,
    module_settings: true,
    module_moderation: true,
    module_management: true,
    module_autopublish: false,
    module_messagelogs: false,
    module_joinmessages: false,
    module_leavemessages: false,
    module_statschannel: false,
    module_customcommands: false,
}